# Version del servicio de yamel y no de docker
version: '3.9'

services: 
# nombre del serivicio, puede ser cualquier nombre
  mongodb:
    image: mongo:5.0
    ports: 
    - 27017:27017
    enviroment: 
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORDroot123
    volumenes: 
    - ./mongo_data:/data/db